### ISSUE TITLE
Please add a MIT license

### ISSUE THREAD

**Issue by harishLinkEZ** [ping9719/OmronFinsTCP.Net#1]

**Comment by ping9719** [comment]
ok

**Comment by harishLinkEZ** [comment]
Thank you, This is a great initiative. A good start to use fins protocol.

**Comment by ping9719** [comment]
这个库可能以后不在维护，新的库（Ping9719.DeviceCommunication）支持6+种协议，5+种PLC，10+种设备（如，刻印，扫码，打印，温控，RFID，FCT，机器人等...）。
This library may not be maintained in the future. The new library (Ping9719. DeviceCommunication) supports 6+protocols, 5+PLCs, and 10+devices (such as engraving, scanning, printing, temperature control, RFID, FCT, robots, etc.).

**Comment by harishLinkEZ** [comment]
Ping9719. DeviceCommunication I am not able to find the library, may be its a private library

**Comment by ping9719** [comment]
DeviceCommunication：https://gitee.com/cquni_mx/baseui/tree/master/Ping9719.DeviceCommunication
DeviceCommunicationUi：https://gitee.com/cquni_mx/baseui/tree/master/Ping9719.DeviceCommunication.WPF
他们都在gitee上，github上完善了才会加入进来。这个库的bug很多，文档也没有，正在生产环境中慢慢的优化。

They are all on Gitee and will only join after they have improved on Github. This library has many bugs and no documentation, and is slowly being optimized in a production environment.
